name: app_lints
description: flutter_travel_audio_guide Team Guidelines and Clean Architecture Boundary Checks (Official Analyzer Plugin)
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  analysis_server_plugin: ^0.3.0
  analyzer: ^10.0.2
  analyzer_plugin: ^0.14.2

dev_dependencies:
  test: ^1.26.0
  very_good_analysis: 10.3.0